---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder
inputs:
  - name: bosh-cpi-src
  - name: bosh-src
outputs:
  - name: stemcell
run:
  path: bosh-cpi-src/ci/stemcell/tasks/build-stemcell.sh
params:
  build_number: replace-me
  os_name:      replace-me
  os_version:   replace-me
  os_image:     replace-me
