---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: frodenas/bosh-google-cpi-boshrelease
    tag: v1
inputs:
  - name: bosh-cpi-src
  - name: stemcell
run:
  path: bosh-cpi-src/ci/stemcell/tasks/publish-stemcell.sh
params:
  google_project:       replace-me
  google_region:        replace-me
  google_zone:          replace-me
  google_json_key_data: replace-me
  google_bucket_name:   replace-me
