---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: frodenas/bosh-google-cpi-boshrelease
    tag: v1
inputs:
  - name: bosh-cpi-src
  - name: version-semver
outputs:
  - name: candidate
run:
  path: bosh-cpi-src/ci/tasks/build-candidate.sh
