---
platform: linux
image: docker:///frodenas/bosh-google-cpi-boshrelease
inputs:
  - name: bosh-cpi-release
  - name: version-semver
outputs:
  - name: candidate
run:
  path: bosh-cpi-release/ci/tasks/build-candidate.sh
