---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
    tag: v1
inputs:
  - name: bosh-cpi-src
  - name: bosh-cpi-release
  - name: bosh-cpi-release-sha1
  - name: release-version-semver
outputs:
  - name: promoted
run:
  path: bosh-cpi-src/ci/tasks/promote-candidate.sh
params:
  release_blobs_access_key: replace-me
  release_blobs_secret_key: replace-me
