---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
    tag: v1
inputs:
  - name: bosh-cpi-src
  - name: stemcell
run:
  path: bosh-cpi-src/ci/tasks/run-int.sh
params:
  google_project:                   replace-me
  google_region:                    replace-me
  google_zone:                      replace-me
  google_json_key_data:             replace-me
  google_network:                   replace-me
  google_subnetwork:                replace-me
  google_subnetwork_range:          replace-me
  google_subnetwork_gw:             replace-me
  google_firewall_internal:         replace-me
  google_firewall_external:         replace-me
  google_address_director:          replace-me
  google_address_static_int:        replace-me
  stemcell_name:                    replace-me
