---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: frodenas/bosh-google-cpi-boshrelease
inputs:
  - name: bosh-cpi-src
run:
  path: bosh-cpi-src/ci/tasks/teardown-infrastructure.sh
params:
  google_project:       replace-me
  google_region:        replace-me
  google_zone:          replace-me
  google_json_key_data: replace-me
