---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: frodenas/bosh-google-cpi-boshrelease
inputs:
  - name: bosh-cpi-src
  - name: bosh-init
  - name: deployment
run:
  path: bosh-cpi-src/ci/tasks/teardown-director.sh
params:
  BOSH_INIT_LOG_LEVEL: warn
