---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: frodenas/bosh-google-cpi-boshrelease
inputs:
  - name: bosh-cpi-src
run:
  path: bosh-cpi-src/ci/tasks/unit-tests.sh
