---
groups:
  - name: light-gce-stemcells
    jobs:
      - ubuntu-trusty-stemcell
      - centos-7-stemcell

jobs:
  - name: ubuntu-trusty-stemcell
    plan:
      - aggregate:
        - {trigger: true, get: stemcell, resource: ubuntu-stemcells}
        - {trigger: false, get: bosh-cpi-src}

      - task: create-light-stemcell
        file: bosh-cpi-src/ci/stemcell/light/tasks/build-light-stemcell.yml
        privileged: true
        params:
          BUCKET_NAME:     {{google_raw_stemcells_bucket_name}}

      - aggregate:
        - put: bosh-ubuntu-raw-stemcells
          params:
            file: raw-stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz
            predefined_acl: "publicRead"

        - put: bosh-ubuntu-light-stemcells
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz
            predefined_acl: "publicRead"

        - put: bosh-ubuntu-raw-stemcells-sha1
          params:
            file: raw-stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz.sha1
            predefined_acl: "publicRead"

        - put: bosh-ubuntu-light-stemcells-sha1
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz.sha1
            predefined_acl: "publicRead"

  - name: centos-7-stemcell
    plan:
      - aggregate:
        - {trigger: true, get: stemcell, resource: centos-stemcells}
        - {trigger: false, get: bosh-cpi-src}

      - task: create-light-stemcell
        file: bosh-cpi-src/ci/stemcell/light/tasks/build-light-stemcell.yml
        privileged: true
        params:
          BUCKET_NAME:     {{google_raw_stemcells_bucket_name}}

      - aggregate:
        - put: bosh-centos-raw-stemcells
          params:
            file: raw-stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent-raw.tar.gz
            predefined_acl: "publicRead"

        - put: bosh-centos-light-stemcells
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz
            predefined_acl: "publicRead"

        - put: bosh-centos-raw-stemcells-sha1
          params:
            file: raw-stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent-raw.tar.gz.sha1
            predefined_acl: "publicRead"

        - put: bosh-centos-light-stemcells-sha1
          params:
            file: light-stemcell/light-bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz.sha1
            predefined_acl: "publicRead"

resources:
  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release.git
      branch: master

  - name: ubuntu-stemcells
    type: s3
    source:
      regexp: bosh-stemcell-(.+)-google-kvm-ubuntu-trusty-go_agent.tgz
      bucket: bosh-google-stemcells-dev

  - name: bosh-ubuntu-raw-stemcells
    type: gcs-resource
    source:
      json_key: {{google_raw_stemcells_json_key_data}}
      bucket:   {{google_raw_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz

  - name: bosh-ubuntu-raw-stemcells-sha1
    type: gcs-resource
    source:
      json_key: {{google_raw_stemcells_json_key_data}}
      bucket:   {{google_raw_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz.sha1

  - name: bosh-ubuntu-light-stemcells
    type: s3
    source:
      bucket:            {{google_light_stemcells_bucket_name}}
      access_key_id:     {{google_light_stemcells_access_key_id}}
      secret_access_key: {{google_light_stemcells_secret_access_key}}
      endpoint:          {{google_light_stemcells_endpoint}}
      region:            {{google_light_stemcells_region}}
      regexp:            light-bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz

  - name: bosh-ubuntu-light-stemcells-sha1
    type: s3
    source:
      bucket:            {{google_light_stemcells_bucket_name}}
      access_key_id:     {{google_light_stemcells_access_key_id}}
      secret_access_key: {{google_light_stemcells_secret_access_key}}
      endpoint:          {{google_light_stemcells_endpoint}}
      region:            {{google_light_stemcells_region}}
      regexp:            light-bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz.sha1

  - name: centos-stemcells
    type: s3
    source:
      regexp: bosh-stemcell-(.+)-google-kvm-centos-7-go_agent.tgz
      bucket: bosh-google-stemcells-dev

  - name: bosh-centos-raw-stemcells
    type: gcs-resource
    source:
      json_key: {{google_raw_stemcells_json_key_data}}
      bucket:   {{google_raw_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent-raw.tar.gz

  - name: bosh-centos-raw-stemcells-sha1
    type: gcs-resource
    source:
      json_key: {{google_raw_stemcells_json_key_data}}
      bucket:   {{google_raw_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent-raw.tar.gz.sha1

  - name: bosh-centos-light-stemcells
    type: s3
    source:
      bucket:            {{google_light_stemcells_bucket_name}}
      access_key_id:     {{google_light_stemcells_access_key_id}}
      secret_access_key: {{google_light_stemcells_secret_access_key}}
      endpoint:          {{google_light_stemcells_endpoint}}
      region:            {{google_light_stemcells_region}}
      regexp:            light-bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent.tgz

  - name: bosh-centos-light-stemcells-sha1
    type: s3
    source:
      bucket:            {{google_light_stemcells_bucket_name}}
      access_key_id:     {{google_light_stemcells_access_key_id}}
      secret_access_key: {{google_light_stemcells_secret_access_key}}
      endpoint:          {{google_light_stemcells_endpoint}}
      region:            {{google_light_stemcells_region}}
      regexp:            light-bosh-stemcell-([0-9\.]+)-google-kvm-centos-7-go_agent.tgz.sha1

resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
