---
platform: linux

image: docker:///bosh/os-image-stemcell-builder

inputs:
  - name: bosh-src
  - name: bosh-cpi-src

outputs:
  - name: stemcell

run:
  path: bosh-cpi-src/ci/stemcell/heavy/tasks/build.sh

params:
  IAAS:                   replace-me
  HYPERVISOR:             replace-me
  OS_NAME:                replace-me
  OS_VERSION:             replace-me
  CANDIDATE_BUILD_NUMBER: replace-me
