---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
    tag: v2

inputs:
  - name: light-stemcell
  - name: bosh-cpi-src

run:
  path: bosh-cpi-src/ci/stemcell/light/tasks/publish-boshio-checksum.sh

params:
  BOSHIO_TOKEN: ""
