---
groups:
  - name: bosh-google-cpi-boshrelease
    jobs:
      - integration

jobs:
  - name: integration
    serial: true
    plan:
      - get: bosh-google-cpi-boshrelease
        trigger: true

      - task: unit-tests
        file: bosh-google-cpi-boshrelease/ci/tasks/unit-tests.yml

resources:
  - name: bosh-google-cpi-boshrelease
    type: git
    source:
      uri: https://github.com/frodenas/bosh-google-cpi-boshrelease.git
      branch: master
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml
