---
groups:
  - name: bosh-google-cpi-boshrelease
    jobs:
      - integration
      - build-candidate

jobs:
  - name: integration
    serial: true
    plan:
      - get: bosh-google-cpi-boshrelease
        trigger: true

      - task: unit-tests
        file: bosh-google-cpi-boshrelease/ci/tasks/unit-tests.yml

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - get: bosh-google-cpi-boshrelease
          trigger: false
          passed:
            - integration
        - get: version-semver
          trigger: false
          params:
            bump: patch

      - put: version-semver
        params:
          file: version-semver/number

      - task: build-release
        file: bosh-google-cpi-boshrelease/ci/tasks/build-candidate.yml

      - put: bosh-google-cpi-dev-artifacts
        params:
          from: candidate/.*\.tgz

resources:
  - name: bosh-google-cpi-boshrelease
    type: git
    source:
      uri: https://github.com/frodenas/bosh-google-cpi-boshrelease.git
      branch: master
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            {{s3_google_cpi_pipeline_bucket_name}}
      access_key_id:     {{s3_google_cpi_pipeline_access_key}}
      secret_access_key: {{s3_google_cpi_pipeline_secret_key}}

  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_google_cpi_pipeline_bucket_name}}
      access_key_id:     {{s3_google_cpi_pipeline_access_key}}
      secret_access_key: {{s3_google_cpi_pipeline_secret_key}}

  - name: bosh-google-cpi-dev-artifacts
    type: s3
    source:
      regexp:            bosh-google-cpi([0-9.]+)\.tgz
      bucket:            {{s3_google_cpi_pipeline_bucket_name}}
      access_key_id:     {{s3_google_cpi_pipeline_access_key}}
      secret_access_key: {{s3_google_cpi_pipeline_secret_key}}
