azs:
- name: z1
  cloud_properties: {zone: REPLACE_ZONE_NAME}
- name: z2
  cloud_properties: {zone: REPLACE_ZONE_NAME}

vm_types:
- name: common
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

- name: worker
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 100
    root_disk_type: pd-ssd

vm_extensions:
- name: concourse-lb
  cloud_properties:
    backend_service: concourse

compilation:
  workers: 2
  network: public
  reuse_compilation_vms: true
  az: z1
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
    preemptible: true

networks:
  - name: public
    type: manual
    subnets:
    - az: z1
      range: REPLACE_SUBNET_RANGE
      gateway: REPLACE_SUBNET_GW
      reserved: [REPLACE_DIRECTOR_STATIC_IP]
      cloud_properties:
        network_name: REPLACE_NETWORK_NAME
        subnetwork_name: REPLACE_SUBNETWORK_NAME
        ephemeral_external_ip: false
        tags:
          - concourse-public
          - concourse-internal
    - az: z2
      range: REPLACE_SUBNET_RANGE
      gateway: REPLACE_SUBNET_GW
      cloud_properties:
        network_name: REPLACE_NETWORK_NAME
        subnetwork_name: REPLACE_SUBNETWORK_NAME
        ephemeral_external_ip: true
        tags:
          - concourse-public
          - concourse-internal

  - name: vip
    type: vip
    
disk_types:
- name: database
  disk_size: 10240
